### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by santiago** [krzysztofzablocki/KZLineDrawer#29]
Hello, great project, thanks.

I'm having trouble building the project, I'm getting CGPointExtension.h file not found. Made some research on this error but nothing worked for me. 

Thanks

**Comment by richardgroves** [comment]
You need to initialise the sub-modules to get the cocos2d library installed (use:  git submodule update --init --recursive).

If you've already done that then you need to make sure the project file includes the cocos2d library and is building it.
