### ISSUE TITLE
merowing?

### ISSUE THREAD

**Issue by bsabiston** [krzysztofzablocki/KZLineDrawer#3]
Hello,

  I wanted to read the blog post about the creation of this, but the link doesn't work.  In fact http://www.merowing.info/ is down ?

I have not looked through the code, but my question is -- how necessary is Cocos 2D, and I was wondering how the antialiasing is done.  Is it texture mapped?

Thanks
Bob

**Comment by MemetiDrak** [comment]
i have some problem with running this project ,can you leave me a email which i can contact with @krzysztofzablocki
