### ISSUE TITLE
xcode telling me cocos2d.h is not found 

### ISSUE THREAD

**Issue by MemetiDrak** [krzysztofzablocki/KZLineDrawer#32]
![wechatimg2](https://cloud.githubusercontent.com/assets/9655508/19519556/1038f82e-963f-11e6-85d0-7afb87df985c.jpeg)

**Comment by MemetiDrak** [comment]
how to fix this problem ,and run demo ,please help

**Comment by MemetiDrak** [comment]
problem solved by running git commend below in my project directory

git submodule update --init --recursive

**Comment by YogendraPatel** [comment]
@MemetGhini @krzysztofzablocki 
I run this command but still i got error "cocos2d.h file not found"

Please help me as soon as possible
